CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  telephone INT(11),
  gender INT(2),
  date_birthday DATE,
  password VARCHAR(55) NOT NULL
);

CREATE TABLE fell (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fell VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE species (
  id INT AUTO_INCREMENT PRIMARY KEY,
  species VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE race (
  id INT AUTO_INCREMENT PRIMARY KEY,
  race VARCHAR(50) UNIQUE NOT NULL,
  species_id INT,
  FOREIGN KEY (species_id) REFERENCES species(id)
);

